### ISSUE TITLE
Include SVM results with tracking

### ISSUE THREAD

**Issue by schollz** [schollz/find#89]
- [x] Remove scaling, as better results are made without scaling
- [x] Add in error handling if .model files don't exist
- [x] Add in error handling if svm program doesn't exist

**Comment by schollz** [comment]
Gaussian filter?
